version: '3'

services:
  masst-web:
    networks:
      - default
      - nginx-net
    build: .
    volumes:
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    ports:
      - "5052:5000"
    command: /app/run_server.sh
    #command: /app/run_dev_server.sh
    restart: always
    environment:
      VIRTUAL_HOST: masst.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: masst.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
      gnpsusername: ${gnpsusername:-defaultusername}
      gnpspassword: ${gnpspassword:-defaultpassword}
    deploy:
      resources:
        limits:
          memory: 4000M

networks:
  nginx-net:
    external:
      name: nginx-net